name: CI

# **What it does**: Runs tests.
# **Why we have it**: Ensures tests pass before merging code.

on:
    push:
        branches:
            - main
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        branches:
            - main
        paths-ignore:
            - "docs/**"
            - "*.md"
        types: [opened, ready_for_review, reopened, synchronize]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    code-quality:
        name: Code Quality
        uses: ./.github/workflows/reusable-code-quality.yml
        permissions:
            contents: read
        secrets: inherit
        with:
            commitlint: true
            lint: false
